### ISSUE TITLE
SVG loading breaks vue production build

### ISSUE THREAD

**Issue by abubics** [dpc-sdp/ripple#903] opened 2021-02-17 00:57 UTC
Hello :) It's a little hard to debug and understand, so there's still a strong chance that this isn't something to fix in ripple, but possibly something to add to docs for ripple users.

| version | issue |
| - | - |
| 1.19.8 | investigated |
| something in November 2020 | raised but not investigated |

We recently inherited a vue app, with an outstanding CI issue, that `vue-cli-service build --mode production` yields a build error (included at the bottom, to reduce noise).

Investigation has been difficult, due to webpack chains being a bit magical. But there are a few things we've found that might be relevant:

1. There is a PR (#774) that removes svg loading rules from the vue example app.
2. Removing `svgRule.uses.clear();` from our `vue.config.json` before the `svg-sprite-loader` rules removes the error (but `vic-logo.svg` is broken).
3. The build error surfaces in `ripple-pagination`, but `separator.svg` remains unaffected if the svg rule is cleared.
4. All the answers I can find on the internet talk about server-side rendering issues, which makes sense in context of the error, but feels like a red herring in context of SVGs.

________

So, hopefully y'all have seen something like this before, and the fix is easy and obvious and we just didn't realise :pray:

But, worst case, something is actually broken, and people haven't noticed (like no one's building vue apps atm, or they haven't noticed the footer is missing an image, or they're deploying staging builds to prod, or who knows).

________

**Build error:**
```
 error  in ./node_modules/@dpc-sdp/ripple-pagination/PrevNext.vue?vue&type=style&index=0&lang=scss&

Syntax Error: ReferenceError: document is not defined


 @ ./node_modules/@dpc-sdp/ripple-pagination/PrevNext.vue?vue&type=style&index=0&lang=scss& 1:0-475 1:0-475
 @ ./node_modules/@dpc-sdp/ripple-pagination/PrevNext.vue
 @ ./node_modules/@dpc-sdp/ripple-pagination/index.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/search/SearchResult.vue?vue&type=script&lang=ts&
 @ ./src/components/search/SearchResult.vue?vue&type=script&lang=ts&
 @ ./src/components/search/SearchResult.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/scheme/SearchScheme.vue?vue&type=script&lang=ts&
 @ ./src/views/scheme/SearchScheme.vue?vue&type=script&lang=ts&
 @ ./src/views/scheme/SearchScheme.vue
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

**Comment by tim-yao** [comment] 2021-02-17 03:08
Thanks @abubics for raise the issue here!

For SVG icons, yes, we did a change on how to add custom icons. However, it's not a breaking change, your app can work without migrating to the new implementation. Do you know if your project has custom Ripple icons? If not, you can just remove old implementation like here https://github.com/dpc-sdp/ripple/pull/774/files#diff-e98f43f1a2c175915ef9aea0f011c5085b58c9fa241d6d20d19a9ef28b00c7eeL1
If you do, you can still remove as above and migrate to the new way to register custom icon https://github.com/dpc-sdp/ripple/blob/master/packages/components/Atoms/Icon/README.md#registering-custom-icons
Examples: https://github.com/dpc-sdp/ripple/tree/master/examples/basic-examples/assets/ripple-icon

For the error:
```
 error  in ./node_modules/@dpc-sdp/ripple-pagination/PrevNext.vue?vue&type=style&index=0&lang=scss&

Syntax Error: ReferenceError: document is not defined
```
I can't reproduce it in my example vue cli app when I add `PrevNext` component then run `vue-cli-service build --mode production`. Also I couldn't see  `document` is used in `PrevNext.vue` so I am not able to debug it. The error self not make much sense to me.

I will suggest try migrate the svg icon then see if the issue fixed.
It also will be helpful if you can create a repo which can reproduce the issue. Cheers!

**Comment by abubics** [comment] 2021-02-17 04:28
Thanks for the quick response, @tim-yao!

I can see a couple of custom `<rpl-icon ...>` tags in the codebase, I'll check them out, and try the new custom registration. If that doesn't get us anywhere, I'll see if we have time to make a repro repo . . . we have some delivery pressure atm.

I did look through the pagination package, and anything else that seemed to be implicated, and (just like you) also couldn't find any `document` references, so I assumed it's something weird in the webpack setup.

And also, since it was raised months ago (before we inherited it), I guessed it's also unlikely to be related to that PR's changes. Thanks for confirming :)

**Comment by tim-yao** [comment] 2021-02-17 22:50
Thanks @abubics It sounds the Webpack build process called some client only code. `document` is a browser only thing. I think your app is a client side app not using server side rendering right? I will leave you to investigate and find more information. Thanks!

**Comment by abubics** [comment] 2021-02-18 03:33
Yeah, exactly. We'll jump back in this thread once we figure more out :)

**Comment by gazal-k** [comment] 2021-02-22 01:49
We figured this out. We were customising the svgRule in `vue.config.js`. We need to use `url-loader` so that https://github.com/dpc-sdp/ripple/blob/dd1afe52b9ecdab8d0d5310eba8984aee5d0b45d/packages/components/Organisms/SiteFooter/SiteFooter.vue#L28 works. The right way to do that seems to be:

```js
    config.module.rule('svg').exclude
      .add(resolve(__dirname, path.dirname(require.resolve('@dpc-sdp/ripple-global/package.json'))));

    config.module
      .rule('svg-url')
      .test(/\.svg$/i)
      .use('url-loader').loader('url-loader')
      .end();
```

**Comment by tim-yao** [comment] 2021-03-01 06:44
Thanks @gazal-k for updating what you got! That make sense if you have your own loader. I will close this issue now as it's resolved in your side.

**Closed by tim-yao** 2021-03-01 06:44 UTC
